USE [master]
GO

/****** Object:  Database [TrekBooking]    Script Date: 10-08-2023 01:24:03 ******/
CREATE DATABASE [TrekBooking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TrekBooking', FILENAME = N'C:\Users\Dell\TrekBooking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TrekBooking_log', FILENAME = N'C:\Users\Dell\TrekBooking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrekBooking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TrekBooking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TrekBooking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TrekBooking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TrekBooking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TrekBooking] SET ARITHABORT OFF 
GO

ALTER DATABASE [TrekBooking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TrekBooking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TrekBooking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TrekBooking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TrekBooking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TrekBooking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TrekBooking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TrekBooking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TrekBooking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TrekBooking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TrekBooking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TrekBooking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TrekBooking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TrekBooking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TrekBooking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TrekBooking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TrekBooking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TrekBooking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TrekBooking] SET  MULTI_USER 
GO

ALTER DATABASE [TrekBooking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TrekBooking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TrekBooking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TrekBooking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TrekBooking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TrekBooking] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TrekBooking] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TrekBooking] SET  READ_WRITE 
GO

